Myprofile/urls.py
# Myprofile/urls.py

from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('resume-download/<str:title>/', views.ResumeDownloadView.as_view(), name='resume-download'),
    path('contact/', views.contact_us, name='contact_us'),
]

blog/urls.py
# notes/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.blog_page, name='blog-page'),
]

notes/urls.py
# notes/urls.py
from django.urls import path
from . import views

app_name = 'notes'

urlpatterns = [
    path('', views.NoteListView.as_view(), name='note-list'),
    path('note-download/<int:pk>/', views.NoteDownloadView.as_view(), name='note-download'),
    path('view-pdf/<int:note_id>/', views.display_pdf, name='display-pdf'),
    # Add more URL patterns for detail and download views if needed
]

portfolio/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static 
from project import views as project_views
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Myprofile.urls')),  # Include the Myprofile app's URLs as the homepage
    path('projects/', include('project.urls', namespace='projects')),
    path('notes/', include('notes.urls', namespace='notes')),
    path('blogs/', include('blog.urls', namespace='blogs')),
    path('<path:invalid_path>', TemplateView.as_view(template_name="portfolio/custom_404.html"), name="catch-all-404"),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path('', views.project_list, name='project_list'),]

Myprofile/models.py
from django.db import models

class ContactMessage(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()
    def __str__(self):
        return self.name

class Resume(models.Model):
    resumetitle = models.CharField(max_length=100)
    pdf_file = models.FileField(upload_to='resumes/')
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.resumetitle

blog/models.py
from django.db import models

# Create your models here.

notes/models.py
# notes/models.py
from django.db import models
from django.utils import timezone
import pytz

class Note(models.Model):
    title = models.CharField(max_length=200)
    pdf_file = models.FileField(upload_to='notes/')
    ist = pytz.timezone('Asia/Kolkata')  # Create a time zone object for IST.
    timestamp = models.DateTimeField(default=timezone.now().astimezone(ist))

    def __str__(self):
        return self.title

project/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='project_images/')
    code_link = models.URLField()

    def __str__(self):
        return self.title

Myprofile/forms.py
# myprofile/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    subject = forms.CharField(max_length=200)
    message = forms.CharField(widget=forms.Textarea)

Myprofile/views.py
# Myprofile/views.py

from django.shortcuts import render, get_object_or_404
from django.http import FileResponse, HttpResponse
from django.conf import settings
import os
from .models import ContactMessage, Resume
from .forms import ContactForm
from django.views import View
from django.http import Http404
from django.core.exceptions import ValidationError

def home(request):
    return render(request, 'Myprofile/profile.html')

class ResumeDownloadView(View):
    def get(self, request, title):
       try:
            resume = get_object_or_404(Resume, resumetitle=str(title))
            response = HttpResponse(resume.pdf_file, content_type='application/pdf')
            response['Content-Disposition'] = f'attachment; filename="Jitesh_shewale_resume.pdf"'
            return response
       except Http404:
            return render(request, 'Myprofile/noresume.html')
       
def contact_us(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        try:
            if form.is_valid():
                name = form.cleaned_data['name']
                email = form.cleaned_data['email']
                subject = form.cleaned_data['subject']
                message = form.cleaned_data['message']

                # Save the message to the database
                ContactMessage.objects.create(
                    name=name,
                    email=email,
                    subject=subject,
                    message=message
                )
                # Redirect or display a thank you page
                return render(request, 'Myprofile/thanku.html')
        except ValidationError as e:
            return HttpResponse('Error with page', status=404)
            form.add_error(None, e)
    else:
        form = ContactForm()

    return render(request, 'Myprofile/contact.html', {'form': form})


def custom_404(request, exception):
    return render(request, '404.html', status=404)

blog/views.py
from django.shortcuts import render
from django.views import View

# Create your views here.
def blog_page(request):
    return render(request, 'blog/index.html')

notes/views.py
from django.views.generic import ListView
from django.views import View
from django.http import FileResponse, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from .models import Note
from django.conf import settings
from django.http import Http404
import mimetypes
import os

class NoteListView(ListView):
    model = Note
    template_name = 'notes/note_list.html'
    context_object_name = 'notes'

class NoteDownloadView(View):
    def get(self, request, pk):
        try:
            note = get_object_or_404(Note, pk=pk)
            response = HttpResponse(note.pdf_file, content_type='application/pdf')
            response['Content-Disposition'] = f'attachment; filename="{note.title}.pdf"'
            return response
        except Http404:
            return HttpResponse("Notes not found", status=404)
    

def display_pdf(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    return render(request, 'notes/display_pdf.html', {'note': note})

project/views.py
from django.shortcuts import render
from .models import Project

def project_list(request):
    projects = Project.objects.all()
    return render(request, 'project/project.html', {'projects': projects})

Myprofile/templates/Myprofile/contact.html
{% extends "portfolio/common.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'Myprofile/contact.css' %}">

    <div class="header text-center">
        <h1>Contact us</h1>
    </div>

    <div class="content">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="contact-form">
                    <h1 class="mb-4">Contact Us</h1>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Send</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Myprofile/templates/Myprofile/noresume.html
{% extends "portfolio/common.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'Myprofile/thanku.css' %}">

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center">
                <div class="thank-you">
                    <h1>Thank You</h1>
                    <p>There is issue with fetching resume...try after some time</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Myprofile/templates/Myprofile/profile.html
{% extends "portfolio/common.html" %}
{% load static %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'Myprofile/profile.css' %}">

    <div class="header text-center">
        <h1>Profile</h1>
    </div>
    
    <div class="container profile-section" style="padding-left: 15px; padding-right: 15px;">
        <div class="row">
            <div class="col-lg-6">
                <h2>Jitesh Shewale</h2>
                <p>Mumbai, Maharashtra-India</p>
                <h3>Education</h3>
                <p>BE (Electronics & Telecommunication)<br>
                Mumbai University<br>
                CGPA: 9.11/10<br>
                Duration: 2017-2021</p>
                <h3>Work Experience</h3>
                <p>Tata Consultancy Services (2021-Current)<br>
                Mumbai, India<br>
                Responsibilities:
                <ul class="responsibilities-list">
                    <li>Utilized Python with PyODBC to query MySQL databases and authenticate connections.</li>
                    <li>Enhanced MySQL database performance by modifying tables, views, and stored procedures.</li>
                    <li>Collaborated with the DBA team to deploy changes in the Redshift database.</li>
                    <li>Developed Autosys jobs, Unix scripts, and email templates using Python and Jinja2.</li>
                    <li>Managed onshore development teams and applied OOP principles in Python scripting.</li>
                    <li>Employed various Python libraries, including pandas, sys, OS, shutil, and subprocess.</li>
                    <li>Developed YAML files to store application-related information.</li>
                    <li>Integrated Veracode Scan into Jenkins for automated code review.</li>
                    <li>Proficient in BitBucket, SourceTree, PyCharm, and other development tools.</li>
                </ul>
            </div>
            <div class="col-lg-6">
                <h3>Certifications</h3>
                <ul class="certification-list">
                    <li><a href="https://www.udemy.com/certificate/UC-dff89f54-1b24-4f74-9bd1-8462e333b87a/" target="_blank">Data Analysis with Python by IBM, Coursera</a></li>
                    <li><a href='https://www.udemy.com/certificate/UC-b3400b74-bbe6-407f-a6d6-c8f7b171caf4/' target='blank_'>Django Masterclass, Udemy</a></li>
                    <li><a href='https://www.coursera.org/account/accomplishments/verify/XPBCMGYNTWPY' target='blank_'>Advanced SQL Retrieval Queries Coursera</a></li>
                    <li><a href='https://www.credly.com/badges/5c2beb9a-c8a6-4dcb-893a-726a8e01e65b/linked_in_profile' target='blank_'>AWS Cloud Practitioner</a></li>
                </ul>
                <h3>Technical Skills</h3>
                <ul class="technical-skills">
                    <li>Languages: Python, SQL, Unix, Java Basic</li>
                    <li>Frameworks: Django</li>
                    <li>Databases: MsSQL, Oracle, Redshift</li>
                    <li>Tools: Bitbucket, SourceTree, Putty, Pycharm</li>
                </ul>
                <h3>Achievements</h3>
                <ul class="achievement-list">
                    <li>Gold Badge in Competitive Programming python Hackerrank, 2020</li>
                    <li>Secured 277th rank in national coding scaler challenge, 2020</li>
                </ul>
                <h3>Off-Work Life</h3>
                <p>
                I'm a junior developer with a love for coding. Outside of work, I find happiness in music, movies, and solo trips. Nature, especially during monsoons and winters, captivates me. I'm not into the club scene or drinking; I prefer classic tunes and rom-com movies. Geopolitics fascinates me because it sheds light on global events. I come from a small village, which keeps me grounded. I might not be a fashion enthusiast, but I appreciate simplicity and real connections. In this diverse blend of interests and values, I'm crafting a unique life story.
                </p>
                <a href="{% url 'resume-download' 'resume' %}" class="btn btn-primary">Download Resume</a>
            </div>
        </div>
    </div>

{% endblock %}

Myprofile/templates/Myprofile/thanku.html
{% extends "portfolio/common.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'Myprofile/thanku.css' %}">

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center">
                <div class="thank-you">
                    <h1>Thank You</h1>
                    <p>Your message has been sent. We will get back to you soon.</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends "portfolio/common.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/blog.css' %}">

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center">
                <div class="thank-you">
                    <h1>Working on the Blog Page</h1>
                    <p>Stay Tuned!!</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

notes/templates/notes/display_pdf.html
 <iframe src="{{ note.pdf_file.url }}" style="width: 100%; height: 500px;"></iframe>

notes/templates/notes/note_list.html
{% extends "portfolio/common.html" %}
{% load static %}

{% block content %}
<div class="header text-center">
    <h1>Notes</h1>
</div>

<div class="container mt-4">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Title</th>
                <th>Created_at</th>
                <th>Download</th>
                <th>View File</th>
            </tr>
        </thead>
        <tbody>
            {% for note in notes %}
            <tr>
                <td>{{ note.title }}</td>
                <td>{{ note.timestamp }}</td>
                <td>
                    <a href="{% url 'notes:note-download' note.pk %}" class="btn btn-primary btn-sm">Download</a>
                </td>
                <td>
                    <a href="{% url 'notes:display-pdf' note.pk %}" class="btn btn-primary btn-sm">View</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

portfolio/templates/portfolio/common.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'portfolio/custom.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>    

    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'project:project_list' %}">Projects</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blogs:blog-page' %}">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contact_us' %}">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'notes:note-list' %}">Notes</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
   
    <div class="content">
       {% block content %}
       {% endblock %}
    </div>

    <footer class="footer text-center">
        <div class="container">
            <p>&copy;2023 My Portfolio Website</p>
            <ul class="list-inline social-icons">
                <li class="list-inline-item">
                    <a href="https://www.instagram.com/just.shewale/" target="_blank">
                        <i class="fab fa-instagram"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="https://www.linkedin.com/in/jitesh-shewale-41ba68195/" target="_blank">
                        <i class="fab fa-linkedin"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="https://github.com/Jitesh001" target="_blank">
                        <i class="fab fa-github"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="https://www.hackerrank.com/profile/jiteshshewale40" target="_blank">
                        <i class="fab fa-hackerrank"></i>
                    </a>
                </li>
                <!-- Add more social media links as needed -->
            </ul>
        </div>
    </footer>

    <!-- Include Bootstrap JavaScript (optional) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"></script>
</body>
</html>

portfolio/templates/portfolio/custom_404.html
<!DOCTYPE html>
<html>
<head>
    <title>Page Not Found</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <h1>Page Not Found</h1>
    <p>The requested page does not exist. Please check the URL and try again.</p>
</body>
</html>

project/templates/project/project.html
{% extends "portfolio/common.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'project/project.css' %}">

<div class="header text-center">
    <h1>My Projects</h1>
</div>

<div class="container project-list mt-4">
    <div class="project-container">
        {% for project in projects %}
        <div class="project-card">
            <img src="/media/project_images/p1.jpg" class="project-image" alt="{{ project.title }}">
            <div class="project-details">
                <h5 class="project-title">{{ project.title }}</h5>
                <p class="project-description">{{ project.description }}</p>
                <a href="{{ project.code_link }}" target="_blank" class="project-link">Code</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}